### ISSUE TITLE
Improved validation of REXS files

### ISSUE THREAD

**Issue by KeuthenFva** [fva-net/rexs-api-java#115]
Currently the validation of REXS files using the Java API is restricted to the following:
- validation of the file format (e.g. usage of correct xml-tags)
- validation of component type for the specified REXS version
- validation of attribute id and unit  for the specified REXS version
- validation of component-attribute-mapping for the specified REXS version

Planned extension of the validation:
- validation of relations, i.e. usage of correct relation types and roles as well as checking if the referenced components in a relation are an allowed combination
- validation of compliance to modelling guideline quasistatic (as optional check)

**Comment by karstenroethig** [comment]
Resolved by #126.
