### ISSUE TITLE
Standard rules for pull requests

### ISSUE THREAD

**Issue by johkoenig** [fva-net/rexs-api-java#125]
I propose to roll out the a few more rules to pull requests:
- [x] At least one reviewer besides the author must approve the PR
- [ ] PRs with all checks completed (build + approval) shall be auto-completed (will not be implemented)
- [x] Branches of PRs shall be deleted after merge

**Comment by johkoenig** [comment]
Providing default reviewers could be done by creating a [`CODEOWNERS`](https://docs.github.com/de/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) file

**Comment by johkoenig** [comment]
@karstenroethig 
See this documentation on protecting branches: https://docs.github.com/de/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule

It should be usable with GitHub Free

**Comment by johkoenig** [comment]
Please check this on automatic branch deletion: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-the-automatic-deletion-of-branches

**Comment by karstenroethig** [comment]
I made the following adjustments via the settings:
* Settings > Gerneral > Pull Requests > Allow merge commits: Disabled
* Settings > Gerneral > Pull Requests > Automatically delete head branches: Enabled
* Settings > Rules > Rulesets > "Basic Ruleset"
	* Target branch: Default (master)
	* Rules:
		* Require linear history: Enabled
		* Require a pull request before merging: Enabled
		* Required approvals: 1

In our next meeting we can look at the other options together and activate them if necessary.

**Comment by johkoenig** [comment]
For the current active PR, I am unable to merge this without your approval. I'm also unable to workaround by self-approving it. Setup looks good, from my side.

**Comment by johkoenig** [comment]
clsd
