### ISSUE TITLE
Inconsistent comparing of RexsVersion objects

### ISSUE THREAD

**Issue by johkoenig** [fva-net/rexs-api-java#133]
The class `RexsVersion` has currently two methods which allow a comparison of versions: `equals` and `compareTo`. The behaviour of both is not consistent, though.

- `equals` compares based on the name. So, if I have `v1 = RexsVersion.create("1.6", 1600)` and `v2 = RexsVersion.create("1.6 extended", 1600)`, the result of `equals` is `False`.
- `compareTo` compares on the number (internally defined as `order`). So, `compareTo` will return `0` for `v1` and `v2`.

I propose to select one field for equality and comparison and apply it to both. I think that the numerical value of `order` is better suited than the name, which is of type `String`.

**Comment by johkoenig** [comment]
Some literature on this topic: https://docs.oracle.com/javase/8/docs/api/java/lang/Comparable.html

**Comment by johkoenig** [comment]
This issue is a little bit more complicated than originally estimated. If we use only the numeric order as datapoint for comparison, it may happen that versions get replaced, for example it `HashSet`s or `HashMap`s. 

Another approach would be to compare both the name and the numeric order. However, this would make it more complicated to order the items accordingly.

**Comment by karstenroethig** [comment]
I suggest that we introduce a Version class that supports the Semantic Versioning format (https://semver.org/). Then we can always sort based on the actual version.

**Comment by johkoenig** [comment]
Good idea. The [semver4j](https://github.com/semver4j/semver4j) library could be used for that. Vendor-specific extensions could be marked as build info, so for example the released version `1.6.0` with ZF-specific extensions would be `1.6.0+ZF`.

**Comment by johkoenig** [comment]
As discussed, we will follow two paths here:
- A new REXS version class (working title `RexsVersion2`) will adopt the existing versioning scheme and remove the double-definition of string number and numeric order.
- It will be adressed in the CCB to adjust the REXS versioning scheme to semantic versioning. It could be adopted for 1.7 (which would be 1.7.0 then). Realistically, however, I think this will not come before version 2.

**Comment by johkoenig** [comment]
I've created the branch [DJK/versioning](https://github.com/fva-net/rexs-api-java/tree/DJK/versioning) with a stub implementation. This should be used as a basis for further discussion.

**Comment by johkoenig** [comment]
@karstenroethig @KeuthenFva Based on your comments, I've re-implemented by stub. It now should fulfill all your requirements.
Please check `DJK/versioning5`. The class is still called `RexsVersion2`, the original implementation has not been replaced yet.
