### ISSUE TITLE
REXS Schema should not contain non-UTF8 characters

### ISSUE THREAD

**Issue by KeuthenFva** [fva-net/rexs-api-java#167]
When parsing the latest REXS DEV model, I was facing some issues as some dashes were not "normal" dashes but special characters from the windows-1252.

0x97: This corresponds to the "em dash" (—) in the Windows-1252 encoding.
0x96: This corresponds to the "en dash" (–) in the Windows-1252 encoding.

The corresponding attributes should be fixed. Also, it should be checked that no non-UTF8 data is entered. This may happen sometimes unintentional when copy-pasting text out of other software.

This issue was carried over from https://access.rexs.info/issues/210

**Comment by johkoenig** [comment]
@karstenroethig: The above-mentioned special dashes are in the descriptions of the enum keys of the attribute `diagram_number_in_iso_281_2007`. This can probably fixed quite easily by updating the descriptions.
Further non-utf8 characters are only in ZF-specific attributes, where I will update them.
